version: '3.6'
services:
  mongo:
    build:
      context: .
    image: mongo
    restart: always
    container_name: mongo
    ports:
      - 9000:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: mongo
