version: '3.6'
services:
  mongo:
    image: mongo
    restart: always
    container_name: mongo
    ports:
      - 9000:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: mongo
  node:
    image: node:latest
    restart: always
    env_file:
     - .env
    container_name: node
    ports:
      - 3000:3000
    volumes:
      - ./src/node:/usr/api
    working_dir: /usr/api
    depends_on:
      - mongo
    command: npm run nodemon-start
  vue:
    image: node:latest
    restart: always
    env_file:
     - .env
    container_name: vue
    ports:
      - 8080:8080
    volumes:
      - ./src/vue:/usr/app
    working_dir: /usr/app
    depends_on:
      - node
    command: npm run serve