version: '3.6'
services:
  mongo:
    image: mongo
    restart: always
    container_name: mongo
    ports:
      - 9000:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: mongo
  node:
    build:
      context: .
      dockerfile: ./node/node.dockerfile
    image: node:latest
    restart: always
    env_file:
     - .env
    container_name: node
    ports:
      - 3000:8081
    volumes:
      - ./src/node:/usr/app
    working_dir: /usr/app
    depends_on:
      - mongo
    command: npm start